name: Build PDF

on:
  push:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build main.pdf
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: -pdf

      - name: Upload main.pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
